module.exports={
    SELLER_COLLECTION:'seller',
    FUEL_COLLECTION:'fuel',
    VEHICLES_COLLECTION:'vehicles',
    DRIVER_COLLECTION:'driver',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    BOOKING_COLLECTION:'booking',
    FEEDBACK_COLLECTION:'feedback'
}